#!/usr/bin/env python3
import os
import re
import argparse
import subprocess
from collections import defaultdict
from concurrent.futures import ThreadPoolExecutor

ARCH_REGEX = re.compile(r"Machine:\s+(.+)")
NEEDED_REGEX = re.compile(r"\(NEEDED\)\s+Shared library: \[(.+)\]")
ARCH_MAP = {
    "Advanced Micro Devices X86-64": "x86-64",
    "Intel 80386": "x86",
    "AArch64": "arm64",
    "ARM": "armv7"
}
ELF_MAGIC = b'\x7fELF'

def check_elf_magic(path):
    try:
        with open(path, 'rb') as f:
            return f.read(4) == ELF_MAGIC
    except Exception:
        return False

def analyze_file(path):
    try:
        arch_proc = subprocess.run(['readelf', '-h', path], capture_output=True, text=True)
        if arch_proc.returncode != 0:
            return None
        
        arch_match = ARCH_REGEX.search(arch_proc.stdout)
        arch = arch_match.group(1).strip() if arch_match else "Unknown"
        arch = ARCH_MAP.get(arch, arch)

        libs_proc = subprocess.run(['readelf', '-d', path], capture_output=True, text=True)
        libs = NEEDED_REGEX.findall(libs_proc.stdout)

        if not libs:
            return None

        return {
            'path': path,
            'arch': arch,
            'libs': libs
        }
    except Exception as e:
        return None

def generate_report(results, output_path=None):
    data = defaultdict(lambda: defaultdict(list))
    
    for item in results:
        for lib in item['libs']:
            data[item['arch']][lib].append(item['path'])

    lines = [
        "Report on dynamic used libraries",
        "Generated by bldd-python-wrapper",
        "=" * 40,
        ""
    ]

    for arch in sorted(data.keys()):
        lines.append(f"---------- {arch} ----------")
        
        libs = data[arch]
        sorted_libs = sorted(libs.items(), key=lambda x: len(x[1]), reverse=True)

        for lib, paths in sorted_libs:
            lines.append(f"{lib} ({len(paths)} execs)")
            for p in paths:
                lines.append(f"\t-> {p}")
        lines.append("")

    report_text = "\n".join(lines)

    if output_path:
        with open(output_path, 'w', encoding='utf-8') as f:
            f.write(report_text)
        print(f"[INFO] Report saved to {output_path}")
    else:
        print(report_text)

def main():
    parser = argparse.ArgumentParser(
        description="bldd (Reverse LDD)",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Usage examples:
  python3 bldd.py -d /usr/bin
  python3 bldd.py --directory /home/user/my_project --output report.txt
        """
    )
    parser.add_argument("-d", "--directory", default="./", help="Directory to scan (by default: ./)")
    parser.add_argument("-o", "--output", help="Path to save report (txt)")
    
    args = parser.parse_args()

    if not os.path.isdir(args.directory):
        print(f"Error: Directory '{args.directory}' does not exist.")
        return

    print(f"[INFO] Scanning directory: {args.directory}")

    all_files = []
    for root, _, files in os.walk(args.directory):
        for name in files:
            full_path = os.path.join(root, name)
            if check_elf_magic(full_path):
                all_files.append(full_path)

    with ThreadPoolExecutor() as executor:
        results = list(filter(None, executor.map(analyze_file, all_files)))

    print(f"[INFO] Scan complete. Found {len(results)} ELF executables.")
    generate_report(results, args.output)

if __name__ == "__main__":
    main()
